# .github/workflows/generate-release-notes.yml
name: Generate Release Notes

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r scripts/requirements.txt

      - name: Generate release notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/generate_release_notes.py --branch ${{ inputs.branch }}
