name: Generate Release Notes

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      branch:
        required: true
        type: string
      days:
        required: false
        type: number
        default: 1
      dry_run:
        required: false
        type: boolean
        default: false

jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout caller repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r scripts/requirements.txt

      - name: Generate release notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/generate_release_notes.py \
            --repo "${{ inputs.repo }}" \
            --branch "${{ inputs.branch }}" \
            --days "${{ inputs.days }}" \
            ${{ inputs.dry_run && '--dry-run' || '' }}
